### ISSUE TITLE
Model fitting produces NaNs for certain inputs

### ISSUE THREAD

**Issue by itdxer** [WillianFuks/pyClickModels#6]
First of all I want to thank you for the library and a great work you did in order to make it work with very efficient implementation.

While using the library I noticed that some of the data that I'm using can converge to NaN values. I managed to find an example that converges to NaN in two iterations

Input json:

```json
{
  "search_keys": {
    "search_term": "xyz"
  },
  "judgment_keys": [
    {
      "session": [
        {"click": 0, "purchase": 0, "doc": "doc0"},
        {"click": 0, "purchase": 0, "doc": "doc1"},
        {"click": 0, "purchase": 0, "doc": "doc2"},
        {"click": 1, "purchase": 1, "doc": "doc3"},
        {"click": 0, "purchase": 0, "doc": "doc4"},
        {"click": 0, "purchase": 0, "doc": "doc5"},
        {"click": 0, "purchase": 0, "doc": "doc6"},
        {"click": 0, "purchase": 0, "doc": "doc7"},
        {"click": 0, "purchase": 0, "doc": "doc8"},
        {"click": 0, "purchase": 0, "doc": "doc9"},
        {"click": 0, "purchase": 0, "doc": "doc10"},
        {"click": 0, "purchase": 0, "doc": "doc11"},
        {"click": 1, "purchase": 1, "doc": "doc12"},
        {"click": 0, "purchase": 0, "doc": "doc13"},
        {"click": 1, "purchase": 0, "doc": "doc14"},
        {"click": 0, "purchase": 0, "doc": "doc15"},
        {"click": 0, "purchase": 0, "doc": "doc16"},
        {"click": 0, "purchase": 0, "doc": "doc17"},
        {"click": 0, "purchase": 0, "doc": "doc18"},
        {"click": 0, "purchase": 0, "doc": "doc19"}
      ]
    }
  ]
}
```

Result after one iterations

```json
{
  "search_term:xyz": {
    "doc18": 0.32974863052368164,
    "doc17": 0.21041131019592285,
    "doc13": 0.1666666716337204,
    "doc12": 0.3333333432674408,
    "doc11": 0.1666666716337204,
    "doc8": 0.1666666716337204,
    "doc16": 0.23937760293483734,
    "doc7": 0.1666666716337204,
    "doc14": 0.26920539140701294,
    "doc3": 0.3333333432674408,
    "doc5": 0.1666666716337204,
    "doc4": 0.1666666716337204,
    "doc9": 0.1666666716337204,
    "doc19": 0.3070479929447174,
    "doc15": 0.2477390617132187,
    "doc0": 0.1666666716337204,
    "doc2": 0.1666666716337204,
    "doc10": 0.1666666716337204,
    "doc6": 0.1666666716337204,
    "doc1": 0.1666666716337204
  }
}
```

Result after two iterations:

```json
{
  "search_term:xyz": {
    "doc18": null,
    "doc17": null,
    "doc13": 0.1666666716337204,
    "doc12": 0.3333333432674408,
    "doc11": 0.1666666716337204,
    "doc8": 0.1666666716337204,
    "doc16": null,
    "doc7": 0.1666666716337204,
    "doc14": null,
    "doc3": 0.3333333432674408,
    "doc5": 0.1666666716337204,
    "doc4": 0.1666666716337204,
    "doc9": 0.1666666716337204,
    "doc19": null,
    "doc15": null,
    "doc0": 0.1666666716337204,
    "doc2": 0.1666666716337204,
    "doc10": 0.1666666716337204,
    "doc6": 0.1666666716337204,
    "doc1": 0.1666666716337204
  }
}
```

It might be just a coincidence, but it looks like nulls only appear in the later documents (from 15th to 20th) and the first null appears at position 15 which is the place where last final happened.

I would appreciate if you can help me to identify the problem.

Let me know if I can provide you with more information.

**Comment by WillianFuks** [comment]
Hi @itdxer ,

Thanks for opening this issue. This is indeed a weird behavior, it does seem to be a bug. I'll further debug it and reply back as soon as I figure out what's happening.

**Comment by WillianFuks** [comment]
Hi @itdxer ,

I've finally debugged the issue and made a few changes.

So what's happening here is that your input data contains two distinct documents that had a purchase (`doc3` and `doc12`). This unfortunately cannot happen due the way the model was implemented. The problem specifically happens in this [line](https://github.com/WillianFuks/pyClickModels/blob/master/pyClickModels/DBN.pyx#L582) of code: once the first purchase is observed then the probability that the customer will continue examining new documents goes to 0 (zero) and therefore when the new purchase happens the result is that it cancels the whole probability making it effectively zero as well.

Later on this value is used as the denominator to find the continuation probability and therefore it gives the error that you observed.

What I did then was to install some exception raising on this step. Unfortunately that's all that can be done in this model as it only allows for 1 purchase.

You can verify if by removing one of the purchases flags if it works on the new code. The new code can be installed with:

    pip install -U pyClickModels==0.0.2rc1

And with the new input data it should work.

Please let me know if this fixes this issue for you :)

Best Regards,

**Comment by itdxer** [comment]
Hi,

Thank you for taking a look and adding exception for this use case. Now I can see that that's the case from the model since `P(S=1|C=1,P=1)=1` and `P(E_r=1|S_{r-1}=1)=0`. I'll add some changes, test a new version and I'll let you know if nans completely disappeared or not.

**Comment by itdxer** [comment]
It looks like when I get rid of the repeated purchases problem gets resolved (at least it converges to some values). Although I've encountered another problematic case. It raises exception which you added, but all of the purchases for this example are equal to zero. It looks like it might be failing because there are too many documents in the list (80 to be precise)

Do you think it might happen because list is to large and calculations might get quite unstable?

Exception:
```
RuntimeError: An error occurred during the optimization process. Please check if your data input files have the correct format, such as each session not having more than 1 sale in total.
```

Input:
```json
{
  "search_keys": {
    "search_term": "xyz"
  },
  "judgment_keys": [
    {
      "session": [
        {"click": 0, "purchase": 0, "doc": "doc0"},
        {"click": 0, "purchase": 0, "doc": "doc1"},
        {"click": 0, "purchase": 0, "doc": "doc2"},
        {"click": 0, "purchase": 0, "doc": "doc3"},
        {"click": 0, "purchase": 0, "doc": "doc4"},
        {"click": 0, "purchase": 0, "doc": "doc5"},
        {"click": 0, "purchase": 0, "doc": "doc6"},
        {"click": 0, "purchase": 0, "doc": "doc7"},
        {"click": 0, "purchase": 0, "doc": "doc8"},
        {"click": 0, "purchase": 0, "doc": "doc9"},
        {"click": 0, "purchase": 0, "doc": "doc10"},
        {"click": 0, "purchase": 0, "doc": "doc11"},
        {"click": 0, "purchase": 0, "doc": "doc12"},
        {"click": 0, "purchase": 0, "doc": "doc13"},
        {"click": 0, "purchase": 0, "doc": "doc14"},
        {"click": 0, "purchase": 0, "doc": "doc15"},
        {"click": 0, "purchase": 0, "doc": "doc16"},
        {"click": 0, "purchase": 0, "doc": "doc17"},
        {"click": 0, "purchase": 0, "doc": "doc18"},
        {"click": 0, "purchase": 0, "doc": "doc19"},
        {"click": 0, "purchase": 0, "doc": "doc20"},
        {"click": 0, "purchase": 0, "doc": "doc21"},
        {"click": 0, "purchase": 0, "doc": "doc22"},
        {"click": 0, "purchase": 0, "doc": "doc23"},
        {"click": 0, "purchase": 0, "doc": "doc24"},
        {"click": 0, "purchase": 0, "doc": "doc25"},
        {"click": 0, "purchase": 0, "doc": "doc26"},
        {"click": 0, "purchase": 0, "doc": "doc27"},
        {"click": 0, "purchase": 0, "doc": "doc28"},
        {"click": 0, "purchase": 0, "doc": "doc29"},
        {"click": 0, "purchase": 0, "doc": "doc30"},
        {"click": 0, "purchase": 0, "doc": "doc31"},
        {"click": 0, "purchase": 0, "doc": "doc32"},
        {"click": 0, "purchase": 0, "doc": "doc33"},
        {"click": 0, "purchase": 0, "doc": "doc34"},
        {"click": 0, "purchase": 0, "doc": "doc35"},
        {"click": 0, "purchase": 0, "doc": "doc36"},
        {"click": 0, "purchase": 0, "doc": "doc37"},
        {"click": 0, "purchase": 0, "doc": "doc38"},
        {"click": 0, "purchase": 0, "doc": "doc39"},
        {"click": 0, "purchase": 0, "doc": "doc40"},
        {"click": 0, "purchase": 0, "doc": "doc41"},
        {"click": 0, "purchase": 0, "doc": "doc42"},
        {"click": 0, "purchase": 0, "doc": "doc43"},
        {"click": 0, "purchase": 0, "doc": "doc44"},
        {"click": 0, "purchase": 0, "doc": "doc45"},
        {"click": 0, "purchase": 0, "doc": "doc46"},
        {"click": 0, "purchase": 0, "doc": "doc47"},
        {"click": 0, "purchase": 0, "doc": "doc48"},
        {"click": 0, "purchase": 0, "doc": "doc49"},
        {"click": 0, "purchase": 0, "doc": "doc50"},
        {"click": 0, "purchase": 0, "doc": "doc51"},
        {"click": 0, "purchase": 0, "doc": "doc52"},
        {"click": 0, "purchase": 0, "doc": "doc53"},
        {"click": 0, "purchase": 0, "doc": "doc54"},
        {"click": 0, "purchase": 0, "doc": "doc55"},
        {"click": 0, "purchase": 0, "doc": "doc56"},
        {"click": 0, "purchase": 0, "doc": "doc57"},
        {"click": 0, "purchase": 0, "doc": "doc58"},
        {"click": 0, "purchase": 0, "doc": "doc59"},
        {"click": 0, "purchase": 0, "doc": "doc60"},
        {"click": 0, "purchase": 0, "doc": "doc61"},
        {"click": 0, "purchase": 0, "doc": "doc62"},
        {"click": 0, "purchase": 0, "doc": "doc63"},
        {"click": 0, "purchase": 0, "doc": "doc64"},
        {"click": 0, "purchase": 0, "doc": "doc65"},
        {"click": 0, "purchase": 0, "doc": "doc66"},
        {"click": 1, "purchase": 0, "doc": "doc67"},
        {"click": 0, "purchase": 0, "doc": "doc68"},
        {"click": 0, "purchase": 0, "doc": "doc69"},
        {"click": 0, "purchase": 0, "doc": "doc70"},
        {"click": 0, "purchase": 0, "doc": "doc71"},
        {"click": 0, "purchase": 0, "doc": "doc72"},
        {"click": 0, "purchase": 0, "doc": "doc73"},
        {"click": 0, "purchase": 0, "doc": "doc74"},
        {"click": 0, "purchase": 0, "doc": "doc75"},
        {"click": 0, "purchase": 0, "doc": "doc76"},
        {"click": 0, "purchase": 0, "doc": "doc77"},
        {"click": 0, "purchase": 0, "doc": "doc78"},
        {"click": 0, "purchase": 0, "doc": "doc79"}
      ]
    }
  ]
}
```

**Comment by WillianFuks** [comment]
Hi @itdxer ,

What happened is that with lots of documents the chain probabilities of clicks at initial points ended up being zero (this is due maximum precision limit) and then some instances of the gamma updating denominator will be zero, which hits the `Exception` installed before.

The unit tests that I set up for the package didn't include this type of data so I didn't realize it. 

I decided then to solve these problems by simply not updating gamma on points where the probability is either close to zero (like 10e-45) or zero itself. This means that your previous data containing two purchases now will work but for the second purchased doc the gamma factor simply won't be updated. Also you can send any amount of given documents for each session and it should work just fine.

Probably the proper approach after all would be to install data validation right at the beginning of code execution (something I haven't implemented yet).

I published an rc with the new code:

    pip install -U pyClickModels==0.0.2rc2


Please let me know if it's working for you now.

Best Regards,

**Comment by itdxer** [comment]
Thank you again for the quick reply and update. I'll try to test it today and I'll let you know about the results.

**Comment by itdxer** [comment]
It looks like everything works, thank you so much for your help!
