### ISSUE TITLE
Not able to pip install on macbook

### ISSUE THREAD

**Issue by mukulsharma9118** [WillianFuks/pyClickModels#9]
**pip install pyClickModels**     
  
Collecting pyClickModels
  Using cached pyClickModels-0.0.2.tar.gz (167 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/username/.virtualenvs/project/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4eda7aacdb76462085bec22ea68494e0/setup.py'"'"'; __file__='"'"'/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4eda7aacdb76462085bec22ea68494e0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-pip-egg-info-r34sbm5i
         cwd: /private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4eda7aacdb76462085bec22ea68494e0/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4eda7aacdb76462085bec22ea68494e0/setup.py", line 158, in <module>
        ext_modules=cythonize(
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyClickModels/DBN.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3f/5f/5229d10f6eec879ad957594e179cc1e320353e4870f77e20987e2cc34117/pyClickModels-0.0.2.tar.gz#sha256=3ac63b80498c74cec1af488a9a934c085be10dce093d380703eea9cf4a0a8ca1 (from https://pypi.org/simple/pyclickmodels/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyClickModels-0.0.1.tar.gz (167 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/username/.virtualenvs/project/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_5f775ef69f4f464b9c1dc572769066db/setup.py'"'"'; __file__='"'"'/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_5f775ef69f4f464b9c1dc572769066db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-pip-egg-info-3nnvo4zu
         cwd: /private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_5f775ef69f4f464b9c1dc572769066db/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_5f775ef69f4f464b9c1dc572769066db/setup.py", line 158, in <module>
        ext_modules=cythonize(
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyClickModels/DBN.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b6/6e/ed40b3e17f85bfd48430b3c101a597cb6baac82cd41c5445b57de48a05aa/pyClickModels-0.0.1.tar.gz#sha256=bcfb2a352966925106f9c11ae96f708132b6430276b7fd3e65b2339f8a37fc7e (from https://pypi.org/simple/pyclickmodels/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyClickModels-0.0.0.tar.gz (170 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/username/.virtualenvs/project/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4586157e779b49808b4d954180a9f488/setup.py'"'"'; __file__='"'"'/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4586157e779b49808b4d954180a9f488/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-pip-egg-info-7v1x5660
         cwd: /private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4586157e779b49808b4d954180a9f488/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hp/p_tnsqq1451f5n9v0z5l08xr0000gn/T/pip-install-_evtqamc/pyclickmodels_4586157e779b49808b4d954180a9f488/setup.py", line 158, in <module>
        ext_modules=cythonize(
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/username/.virtualenvs/project/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyClickModels/DBN.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/a3/9518743addb2593dfbd9e4d7ec0bb22e3fae73c573615c4e4aa84ac4c4c9/pyClickModels-0.0.0.tar.gz#sha256=e6c58070cda55a63ba39c491f1a5b55ce65f50b9995375101deb4ca10d62e0e7 (from https://pypi.org/simple/pyclickmodels/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by WillianFuks** [comment]
Hi @mukulsharma9118 ,

This package was mainly implemented on Linux based OS systems (it's still possible to add up new systems but unfortunately for now I don't have available time for doing so).

What I recommend is trying to run it on top of Docker, installation and execution should be straightforward.

**Comment by mukulsharma9118** [comment]
Thanks @WillianFuks will try with docker. 
I can try to help in adding support for Mac. It would be helpful if you can point me to some documentation on getting started.

**Comment by WillianFuks** [comment]
Hi @mukulsharma9118 ,

I unfortunately don't have much knowledge on building the wheels for Mac OS :(

In this project I used the [manylinux](https://github.com/WillianFuks/pyClickModels/blob/master/scripts/build_wheels.sh#L1) Docker for the build process. I suppose something related should be used for Mac.

**Comment by arian** [comment]
fyi, I got building working on Mac OS m1 with these changes

```bash
brew install json-c
```

```diff
diff --git a/pyClickModels/jsonc.pxd b/pyClickModels/jsonc.pxd
index f426ff0..e482b22 100644
--- a/pyClickModels/jsonc.pxd
+++ b/pyClickModels/jsonc.pxd
@@ -1,4 +1,4 @@
-cdef extern from "/usr/include/json-c/json.h":
+cdef extern from "/opt/homebrew/opt/json-c/include/json-c/json.h":
     struct json_object:
         pass

diff --git a/setup.py b/setup.py
index e9e1bff..2f5bfe0 100644
--- a/setup.py
+++ b/setup.py
@@ -90,6 +90,7 @@ ext_modules = [
         ['pyClickModels/DBN.pyx'],
         language='c++',
         libraries=['json-c'],
+        library_dirs=['/opt/homebrew/opt/json-c/lib/'],
         include_dirs=['pyClickModels'],
         define_macros=define_macros,
         extra_compile_args=["-std=c++11"],
@@ -100,6 +101,7 @@ ext_modules = [
         ['tests/test_cy_DBN.pyx'],
         language='c++',
         libraries=['json-c'],
+        library_dirs=['/opt/homebrew/opt/json-c/lib/'],
         extra_compile_args=["-std=c++11"],
         extra_link_args=["-std=c++11"]
     )
```
